[package]
name = "kssm-stupid-machine"
version = "0.1.0"
edition = "2021"

rust-version = "1.66.0"

readme = "README.md"
repository = "https://github.com/KaiquePacheco/Kaique-s-Stupid-Simulated-Machine-KSSM"

authors = ["Kaique Pacheco kaique12br@gmail.com"]
